/**
 *
 */
package in.wordofgod.bible.converter;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.net.URISyntaxException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;

import in.wordofgod.bible.parser.Bible;
import in.wordofgod.bible.parser.BookID;
import in.wordofgod.bible.parser.TheWord;
import in.wordofgod.bible.parser.vosgson.Book;
import in.wordofgod.bible.parser.vosgson.Chapter;
import in.wordofgod.bible.parser.vosgson.Verse;

/**
 * Converts Bible text to CSV format.
 * Produces four separate UTF-8 CSV files named after the Bible abbreviation:
 *   1. &lt;abbr&gt;_info.csv       — key/value metadata about the Bible translation
 *   2. &lt;abbr&gt;_verses.csv     — every verse (book no, book name, chapter, verse, text)
 *   3. &lt;abbr&gt;_books.csv      — books present in this Bible with chapter counts
 *   4. &lt;abbr&gt;_books_all.csv  — all 66 canonical books, flagging which ones are present
 */
public class CSV {

    public static void createCSV() throws URISyntaxException {
        System.out.println("CSV Creation Started...");
        File file = new File(BibleConverter.bibleSourcePath);

        System.out.println("TheWord Bible loading started...");
        Bible bible;
        try {
            bible = TheWord.getBible(file.getAbsolutePath(), BibleConverter.bibleInformationPath);
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }
        if (bible != null) {
            System.out.println("TheWord Bible loaded successfully...");
        }

        Utils.setOutputFolder(bible.getLanguageCode());

        // Create output directory
        File outputDir = new File(BibleConverter.outputPath);
        if (!outputDir.exists()) {
            outputDir.mkdirs();
            System.out.println("Created output directory: " + outputDir.getAbsolutePath());
        }

        String abbr = bible.getAbbr();

        writeInfoCSV    (bible, abbr);
        writeVersesCSV  (bible, abbr);
        writeBooksCSV   (bible, abbr);
        writeBooksAllCSV(bible, abbr);

        System.out.println("CSV Creation Completed.");
    }

    // -------------------------------------------------------------------------
    // File 1 — info
    // -------------------------------------------------------------------------

    /**
     * Columns: Property, Value
     */
    private static void writeInfoCSV(Bible bible, String abbr) {
        String filePath = BibleConverter.outputPath + File.separator + abbr + "_info.csv";
        String today = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));

        Object[][] rows = {
            { "Abbreviation",           nullSafe(bible.getAbbr()) },
            { "Common Name",            nullSafe(bible.getCommonName()) },
            { "Short Name",             nullSafe(bible.getShortName()) },
            { "Long Name",              nullSafe(bible.getLongName()) },
            { "Long English Name",      nullSafe(bible.getLongEnglishName()) },
            { "Language Code",          nullSafe(bible.getLanguageCode()) },
            { "Published Year",         nullSafe(bible.getPublishedYear()) },
            { "Published By",           nullSafe(bible.getPublishedBy()) },
            { "Translated By",          nullSafe(bible.getTranslatedBy()) },
            { "Copyright",              nullSafe(bible.getCopyRight()) },
            { "Additional Information", nullSafe(bible.getAdditionalInformation()) },
            { "Has OT",                 bible.isHasOT() ? "Yes" : "No" },
            { "Has NT",                 bible.isHasNT() ? "Yes" : "No" },
            { "Total Books",            bible.getTotalBooks() },
            { "Total Chapters",         bible.getTotalChapters() },
            { "Total Verses",           bible.getTotalVerses() },
            { "Total Words",            bible.getTotalWords() },
            { "Total Unique Words",     bible.getTotalUniqueWords() },
            { "Generated Date",         today },
            { "Generated By",           "BibleConverter https://github.com/yesudas/bible-converter" },
        };

        try (BufferedWriter bw = newWriter(filePath)) {
            bw.write(escapeCsv("Property") + "," + escapeCsv("Value"));
            bw.newLine();
            for (Object[] row : rows) {
                bw.write(escapeCsv(row[0].toString()) + "," + escapeCsv(row[1].toString()));
                bw.newLine();
            }
            System.out.println("info CSV written: " + filePath);
        } catch (IOException e) {
            System.err.println("Error writing info CSV: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // -------------------------------------------------------------------------
    // File 2 — verses
    // -------------------------------------------------------------------------

    /**
     * Columns: Book No, Book Name, Chapter, Verse, Scripture
     */
    private static void writeVersesCSV(Bible bible, String abbr) {
        String filePath = BibleConverter.outputPath + File.separator + abbr + "_verses.csv";
        int rowCount = 0;

        try (BufferedWriter bw = newWriter(filePath)) {
            bw.write(escapeCsv("Book No") + "," + escapeCsv("Book Name") + ","
                   + escapeCsv("Chapter") + "," + escapeCsv("Verse") + "," + escapeCsv("Scripture"));
            bw.newLine();

            for (Book book : bible.getBooks()) {
                int bookNumber = getBookNumber(book);
                String bookName = nullSafe(book.getLongName());

                int chapterCount = 0;
                for (Chapter chapter : book.getChapters()) {
                    chapterCount++;
                    int chapterNum = parseIntSafe(chapter.getChapter(), chapterCount);

                    for (Verse verse : chapter.getVerses()) {
                        String text = verse.getUnParsedText();
                        if (text == null || text.trim().isEmpty()) continue;
                        int verseNum = parseIntSafe(verse.getNumber(), 0);
                        if (verseNum <= 0) continue;

                        bw.write(bookNumber + "," + escapeCsv(bookName) + ","
                               + chapterNum + "," + verseNum + "," + escapeCsv(text));
                        bw.newLine();
                        rowCount++;
                    }
                }
            }
            System.out.println("verses CSV rows written: " + rowCount + " → " + filePath);
        } catch (IOException e) {
            System.err.println("Error writing verses CSV: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // -------------------------------------------------------------------------
    // File 3 — books
    // -------------------------------------------------------------------------

    /**
     * Columns: Book No, OSIS ID, Short Name, Long Name, English Name, Chapters
     */
    private static void writeBooksCSV(Bible bible, String abbr) {
        String filePath = BibleConverter.outputPath + File.separator + abbr + "_books.csv";

        try (BufferedWriter bw = newWriter(filePath)) {
            bw.write(escapeCsv("Book No") + "," + escapeCsv("OSIS ID") + ","
                   + escapeCsv("Short Name") + "," + escapeCsv("Long Name") + ","
                   + escapeCsv("English Name") + "," + escapeCsv("Chapters"));
            bw.newLine();

            for (Book book : bible.getBooks()) {
                int bookNumber = getBookNumber(book);
                bw.write(bookNumber + ","
                       + escapeCsv(nullSafe(book.getBookId())) + ","
                       + escapeCsv(nullSafe(book.getShortName())) + ","
                       + escapeCsv(nullSafe(book.getLongName())) + ","
                       + escapeCsv(nullSafe(book.getEnglishName())) + ","
                       + book.getChapters().size());
                bw.newLine();
            }
            System.out.println("books CSV written: " + filePath);
        } catch (IOException e) {
            System.err.println("Error writing books CSV: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // -------------------------------------------------------------------------
    // File 4 — books_all
    // -------------------------------------------------------------------------

    /**
     * Columns: Book No, OSIS ID, English Name, Testament, Present, Chapters
     */
    private static void writeBooksAllCSV(Bible bible, String abbr) {
        String filePath = BibleConverter.outputPath + File.separator + abbr + "_books_all.csv";

        // Build a quick lookup: ZefID → Book
        Map<Integer, Book> presentBooks = new HashMap<>();
        for (Book book : bible.getBooks()) {
            int zefId = getBookNumber(book);
            if (zefId > 0) presentBooks.put(zefId, book);
        }

        try (BufferedWriter bw = newWriter(filePath)) {
            bw.write(escapeCsv("Book No") + "," + escapeCsv("OSIS ID") + ","
                   + escapeCsv("Book Name") + "," + escapeCsv("Testament") + ","
                   + escapeCsv("Present") + "," + escapeCsv("Chapters"));
            bw.newLine();

            for (int zefId = 1; zefId <= 66; zefId++) {
                BookID bid;
                try {
                    bid = BookID.fromZefId(zefId);
                } catch (IllegalArgumentException e) {
                    continue;
                }

                Book present = presentBooks.get(zefId);
                boolean isPresent = present != null;
                int chapters = isPresent ? present.getChapters().size() : 0;
                // Use localized name when available, fall back to English
                String bookName = isPresent ? nullSafe(present.getLongName()) : bid.getEnglishName();

                bw.write(zefId + ","
                       + escapeCsv(bid.getOsisID()) + ","
                       + escapeCsv(bookName) + ","
                       + escapeCsv(bid.isNT() ? "NT" : "OT") + ","
                       + escapeCsv(isPresent ? "Yes" : "No") + ","
                       + chapters);
                bw.newLine();
            }
            System.out.println("books_all CSV written: " + filePath);
        } catch (IOException e) {
            System.err.println("Error writing books_all CSV: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Opens a UTF-8 BufferedWriter for the given file path.
     */
    private static BufferedWriter newWriter(String filePath) throws IOException {
        return new BufferedWriter(new OutputStreamWriter(new FileOutputStream(filePath), "UTF-8"));
    }

    /**
     * Wraps a field value in double-quotes and escapes any embedded double-quotes
     * per RFC 4180 (double-quote is escaped as two double-quotes).
     */
    private static String escapeCsv(String value) {
        if (value == null) value = "";
        // Always quote — keeps Unicode (Tamil, etc.) and commas/newlines safe
        return "\"" + value.replace("\"", "\"\"") + "\"";
    }

    private static int getBookNumber(Book book) {
        if (book.getId() != null) {
            return book.getId().getZefID();
        }
        if (book.getBookId() != null && !book.getBookId().isEmpty()) {
            try {
                return BookID.fromOsisId(book.getBookId()).getZefID();
            } catch (IllegalArgumentException ignored) {
                // fall through
            }
        }
        return book.getBookNo();
    }

    private static int parseIntSafe(String value, int fallback) {
        if (value == null || value.trim().isEmpty()) return fallback;
        try {
            return Integer.parseInt(value.trim());
        } catch (NumberFormatException e) {
            return fallback;
        }
    }

    private static String nullSafe(String value) {
        return value != null ? value : "";
    }
}