/**
 * 
 */
package in.wordofgod.bible.converter;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import in.wordofgod.bible.parser.Bible;
import in.wordofgod.bible.parser.TheWord;
import in.wordofgod.bible.parser.vosgson.Book;
import in.wordofgod.bible.parser.vosgson.Chapter;
import in.wordofgod.bible.parser.vosgson.Verse;

/**
 * Converts Bible text to HTML format.
 * Creates one HTML page per book and a main index.html with table of contents.
 */
public class HTML {

	private static final String FOOTER =
			"<footer>\n" +
			"  <p>Created using <a href=\"https://github.com/yesudas/bible-converter\" target=\"_blank\">BibleConverter</a> program &mdash; " +
			"<a href=\"https://www.WordOfGod.in\" target=\"_blank\">www.WordOfGod.in</a></p>\n" +
			"</footer>\n";

	public static void createHTML() {
		System.out.println("HTML Creation Started...");
		File file = new File(BibleConverter.bibleSourcePath);

		System.out.println("TheWord Bible loading started...");
		Bible bible;
		try {
			bible = TheWord.getBible(file.getAbsolutePath(), BibleConverter.bibleInformationPath);
		} catch (IOException e) {
			e.printStackTrace();
			return;
		}
		if (bible != null) {
			System.out.println("TheWord Bible loaded successfully...");
		}

		try {
			Utils.setOutputFolder(bible.getLanguageCode());
		} catch (java.net.URISyntaxException e) {
			e.printStackTrace();
			return;
		}

		// Create output directory
		try {
			Files.createDirectories(Path.of(BibleConverter.outputPath));
		} catch (IOException e) {
			e.printStackTrace();
			return;
		}

		// Build index.html table-of-contents entries while creating book pages
		StringBuilder tocRows = new StringBuilder();

		for (Book book : bible.getBooks()) {
			String bookFileName = getBookFileName(book);
			createBookPage(bible, book, bookFileName);

			tocRows.append("    <tr>\n");
			tocRows.append("      <td>").append(book.getBookNo()).append("</td>\n");
			tocRows.append("      <td><a href=\"").append(bookFileName).append("\">")
					.append(escapeHtml(book.getLongName())).append("</a></td>\n");
			tocRows.append("      <td>").append(escapeHtml(book.getEnglishName())).append("</td>\n");
			tocRows.append("      <td>").append(book.getChapters().size()).append("</td>\n");
			tocRows.append("    </tr>\n");
		}

		createIndexPage(bible, tocRows.toString());

		System.out.println("HTML Creation Completed...");
		System.out.println("Results are saved in the directory: " + BibleConverter.outputPath);
	}

	// -------------------------------------------------------------------------
	// Index page
	// -------------------------------------------------------------------------

	private static void createIndexPage(Bible bible, String tocRows) {
		StringBuilder sb = new StringBuilder();
		sb.append(htmlHead(escapeHtml(bible.getCommonName()), "style.css"));
		sb.append("<body>\n");
		sb.append(header(bible.getCommonName()));

		// Bible information table
		sb.append("<main>\n");
		sb.append("<section class=\"bible-info\">\n");
		sb.append("<h2>Bible Information</h2>\n");
		sb.append("<table class=\"info-table\">\n");
		sb.append(infoRow("Abbr",                   bible.getAbbr()));
		sb.append(infoRow("Common Name",             bible.getCommonName()));
		sb.append(infoRow("Short Name",              bible.getShortName()));
		sb.append(infoRow("Long Name",               bible.getLongName()));
		sb.append(infoRow("Long English Name",       bible.getLongEnglishName()));
		sb.append(infoRow("Language Code",           bible.getLanguageCode()));
		sb.append(infoRow("Published Year",          bible.getPublishedYear()));
		sb.append(infoRow("Published By",            bible.getPublishedBy()));
		sb.append(infoRow("Translated By",           bible.getTranslatedBy()));
		sb.append(infoRow("Copyright",               bible.getCopyRight()));
		sb.append(infoRow("Additional Information",  bible.getAdditionalInformation()));
		sb.append(infoRow("Total Books",             String.valueOf(bible.getTotalBooks())));
		sb.append(infoRow("Total Chapters",          String.valueOf(bible.getTotalChapters())));
		sb.append(infoRow("Total Verses",            String.valueOf(bible.getTotalVerses())));
		sb.append(infoRow("Total Words",             String.valueOf(bible.getTotalWords())));
		sb.append(infoRow("Total Unique Words",      String.valueOf(bible.getTotalUniqueWords())));
		sb.append(infoRow("Has OT",                  String.valueOf(bible.isHasOT())));
		sb.append(infoRow("Has NT",                  String.valueOf(bible.isHasNT())));
		sb.append(infoRow("Generated By",
				"<a href=\"https://github.com/yesudas/bible-converter\" target=\"_blank\">Created using BibleConverter program</a>"));
		sb.append("</table>\n");
		sb.append("</section>\n");

		// Table of contents
		sb.append("<section class=\"toc\">\n");
		sb.append("<h2>Table of Contents</h2>\n");
		sb.append("<table class=\"toc-table\">\n");
		sb.append("  <thead><tr><th>#</th><th>Book Name</th><th>English Name</th><th>Chapters</th></tr></thead>\n");
		sb.append("  <tbody>\n");
		sb.append(tocRows);
		sb.append("  </tbody>\n");
		sb.append("</table>\n");
		sb.append("</section>\n");
		sb.append("</main>\n");

		sb.append(FOOTER);
		sb.append("</body>\n</html>\n");

		writeFile("index.html", sb.toString());
		writeStylesheet();
	}

	// -------------------------------------------------------------------------
	// Book page
	// -------------------------------------------------------------------------

	private static void createBookPage(Bible bible, Book book, String bookFileName) {
		StringBuilder sb = new StringBuilder();
		String title = escapeHtml(bible.getCommonName()) + " — " + escapeHtml(book.getLongName());
		sb.append(htmlHead(title, "style.css"));
		sb.append("<body>\n");
		sb.append(header(bible.getCommonName()));

		sb.append("<main>\n");
		sb.append("<nav class=\"breadcrumb\"><a href=\"index.html\">&#8592; Table of Contents</a></nav>\n");
		sb.append("<h2 class=\"book-title\">").append(escapeHtml(book.getLongName())).append("</h2>\n");

		// Chapter navigation anchors at top
		sb.append("<nav class=\"chapter-nav\">\n");
		for (Chapter chapter : book.getChapters()) {
			String ch = chapter.getChapter();
			sb.append("<a href=\"#chapter-").append(ch).append("\">").append(ch).append("</a> ");
		}
		sb.append("\n</nav>\n");

		// Chapters and verses
		for (Chapter chapter : book.getChapters()) {
			String ch = chapter.getChapter();
			sb.append("<section class=\"chapter\" id=\"chapter-").append(ch).append("\">\n");
			sb.append("<h3>").append(escapeHtml(book.getLongName())).append(" ").append(ch).append("</h3>\n");
			sb.append("<div class=\"verses\">\n");
			for (Verse verse : chapter.getVerses()) {
				sb.append("<p class=\"verse\" id=\"v").append(ch).append("-").append(verse.getNumber()).append("\">");
				sb.append("<sup class=\"verse-num\">").append(verse.getNumber()).append("</sup> ");
				sb.append(escapeHtml(verse.getUnParsedText()));
				sb.append("</p>\n");
			}
			sb.append("</div>\n");
			sb.append("<a class=\"back-to-top\" href=\"#top\">&#8593; Top</a>\n");
			sb.append("</section>\n");
		}

		sb.append("</main>\n");
		sb.append(FOOTER);
		sb.append("</body>\n</html>\n");

		writeFile(bookFileName, sb.toString());
	}

	// -------------------------------------------------------------------------
	// Stylesheet
	// -------------------------------------------------------------------------

	private static void writeStylesheet() {
		String css =
			"/* BibleConverter HTML output stylesheet */\n" +
			"* { box-sizing: border-box; margin: 0; padding: 0; }\n" +
			"body { font-family: 'Segoe UI', Arial, sans-serif; background: #f9f7f1; color: #222; line-height: 1.8; font-size: 1rem; }\n" +
			"header { background: #4a2c0a; color: #fff; padding: 1.2rem 2rem; }\n" +
			".header-inner { display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 0.5rem; }\n" +
			"header h1 { font-size: 1.8rem; }\n" +
			".font-controls { display: flex; align-items: center; gap: 0.4rem; }\n" +
			".font-controls button { background: rgba(255,255,255,0.15); color: #fff; border: 1px solid rgba(255,255,255,0.4); " +
			"  border-radius: 4px; padding: 0.25rem 0.6rem; cursor: pointer; font-size: 0.9rem; line-height: 1; transition: background 0.2s; }\n" +
			".font-controls button:hover { background: #d4a853; color: #000; border-color: #d4a853; }\n" +
			".font-controls button:nth-child(2) { font-weight: bold; }\n" +
			"main { max-width: 960px; margin: 2rem auto; padding: 0 1rem; }\n" +
			"h2 { color: #4a2c0a; margin: 1.5rem 0 0.75rem; border-bottom: 2px solid #d4a853; padding-bottom: 0.3rem; }\n" +
			"h3 { color: #6b3f14; margin: 1.2rem 0 0.5rem; }\n" +
			".bible-info { margin-bottom: 2rem; }\n" +
			".info-table { width: 100%; border-collapse: collapse; }\n" +
			".info-table tr:nth-child(even) { background: #f0e8d8; }\n" +
			".info-table td { padding: 0.4rem 0.8rem; border: 1px solid #ddd; }\n" +
			".info-table td:first-child { font-weight: bold; width: 220px; color: #4a2c0a; }\n" +
			".toc-table { width: 100%; border-collapse: collapse; }\n" +
			".toc-table thead tr { background: #4a2c0a; color: #fff; }\n" +
			".toc-table th, .toc-table td { padding: 0.5rem 0.8rem; border: 1px solid #ddd; text-align: left; }\n" +
			".toc-table tr:nth-child(even) { background: #f0e8d8; }\n" +
			".toc-table a { color: #4a2c0a; text-decoration: none; font-weight: bold; }\n" +
			".toc-table a:hover { text-decoration: underline; }\n" +
			".breadcrumb { margin-bottom: 1rem; }\n" +
			".breadcrumb a { color: #4a2c0a; text-decoration: none; font-weight: bold; }\n" +
			".breadcrumb a:hover { text-decoration: underline; }\n" +
			".book-title { font-size: 1.6rem; }\n" +
			".chapter-nav { margin: 1rem 0; display: flex; flex-wrap: wrap; gap: 0.3rem; }\n" +
			".chapter-nav a { background: #4a2c0a; color: #fff; padding: 0.2rem 0.6rem; border-radius: 4px; " +
			"  text-decoration: none; font-size: 0.85rem; }\n" +
			".chapter-nav a:hover { background: #d4a853; color: #000; }\n" +
			".chapter { margin-bottom: 2rem; padding-bottom: 1rem; border-bottom: 1px solid #ddd; }\n" +
			".verses { text-align: justify; }\n" +
			".verse { display: block; margin: 0.2rem 0; padding: 0.15rem 0; border-bottom: 1px dotted #e8dcc8; }\n" +
			".verse-num { font-size: 0.75rem; font-weight: bold; color: #4a2c0a; vertical-align: super; margin-right: 2px; }\n" +
			".back-to-top { display: inline-block; margin-top: 0.5rem; font-size: 0.8rem; color: #4a2c0a; text-decoration: none; }\n" +
			".back-to-top:hover { text-decoration: underline; }\n" +
			"footer { background: #4a2c0a; color: #ccc; text-align: center; padding: 1rem; margin-top: 3rem; font-size: 0.85rem; }\n" +
			"footer a { color: #d4a853; text-decoration: none; }\n" +
			"footer a:hover { text-decoration: underline; }\n" +
			"@media (max-width: 600px) {\n" +
			"  header h1 { font-size: 1.2rem; }\n" +
			"  .info-table td:first-child { width: 140px; }\n" +
			"  .font-controls button { padding: 0.2rem 0.45rem; font-size: 0.8rem; }\n" +
			"}\n";

		// Write to parent of outputPath so all book pages can share one stylesheet
		try {
			Path cssPath = Path.of(BibleConverter.outputPath).resolve("style.css");
			Files.writeString(cssPath, css);
			System.out.println("Created stylesheet: " + cssPath);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	// -------------------------------------------------------------------------
	// Helpers
	// -------------------------------------------------------------------------

	private static String htmlHead(String title, String cssPath) {
		return "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n" +
				"<meta charset=\"UTF-8\">\n" +
				"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" +
				"<title>" + title + "</title>\n" +
				"<link rel=\"stylesheet\" href=\"" + cssPath + "\">\n" +
				"</head>\n" +
				"<script>\n" +
				"  const BASE_SIZE = 16;\n" +
				"  const MIN_SIZE  = 10;\n" +
				"  const MAX_SIZE  = 32;\n" +
				"  const STEP      = 2;\n" +
				"  const KEY       = 'bibleFontSize';\n" +
				"  function applySize(px) {\n" +
				"    document.documentElement.style.fontSize = px + 'px';\n" +
				"  }\n" +
				"  function changeFontSize(delta) {\n" +
				"    var current = parseInt(localStorage.getItem(KEY)) || BASE_SIZE;\n" +
				"    var next = Math.min(MAX_SIZE, Math.max(MIN_SIZE, current + delta * STEP));\n" +
				"    localStorage.setItem(KEY, next);\n" +
				"    applySize(next);\n" +
				"  }\n" +
				"  function resetFontSize() {\n" +
				"    localStorage.setItem(KEY, BASE_SIZE);\n" +
				"    applySize(BASE_SIZE);\n" +
				"  }\n" +
				"  (function() {\n" +
				"    var saved = localStorage.getItem(KEY);\n" +
				"    if (saved) applySize(parseInt(saved));\n" +
				"  })();\n" +
				"</script>\n";
	}

	private static String header(String commonName) {
		return "<header id=\"top\">\n" +
				"  <div class=\"header-inner\">\n" +
				"    <h1>" + escapeHtml(commonName) + "</h1>\n" +
				"    <div class=\"font-controls\">\n" +
				"      <button onclick=\"changeFontSize(-1)\" title=\"Decrease font size\">A&minus;</button>\n" +
				"      <button onclick=\"resetFontSize()\"   title=\"Reset font size\">A</button>\n" +
				"      <button onclick=\"changeFontSize(1)\"  title=\"Increase font size\">A+</button>\n" +
				"    </div>\n" +
				"  </div>\n" +
				"</header>\n";
	}

	private static String infoRow(String label, String value) {
		if (value == null || value.trim().isEmpty()) return "";
		return "<tr><td>" + escapeHtml(label) + "</td><td>" + value + "</td></tr>\n";
	}

	private static String getBookFileName(Book book) {
		String bookNo = String.format("%02d", book.getBookNo());
		// Sanitise book name — keep only alphanumeric, spaces, hyphens
		String safeName = book.getEnglishName() != null && !book.getEnglishName().isEmpty()
				? book.getEnglishName()
				: book.getLongName();
		safeName = safeName.replaceAll("[^a-zA-Z0-9\\-]", "_");
		return bookNo + "-" + safeName + ".html";
	}

	private static String escapeHtml(String text) {
		if (text == null) return "";
		return text.replace("&", "&amp;")
				   .replace("<", "&lt;")
				   .replace(">", "&gt;")
				   .replace("\"", "&quot;")
				   .replace("'", "&#39;");
	}

	private static void writeFile(String fileName, String content) {
		try {
			Path path = Path.of(BibleConverter.outputPath + File.separator + fileName);
			Files.createDirectories(path.getParent());
			Files.writeString(path, content);
			System.out.println("Created: " + fileName);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
